#!/usr/bin/env zsh

usage() {
	[[ "$#" > 0 ]] && echo "$1"
	echo "usage brrr search <package>\n"

	if [[ "$#" > 0 ]]; then
		exit 1
	else
		exit 0
	fi
}

search_github() {
	local -r query="$1"
	curl -L -s "https://api.github.com/search/repositories?q=$query" | jq '.items[].full_name'
}


[[ "$1" == '--help' || "$1" == '-h' ]] && usage
[[ "$#" == 0 ]] && usage "Missing package args"

shift 1
search_github "$1"
